### ISSUE TITLE
The package name is confusing

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/libhildon#3]
- Source package is called libhildon
- Installed packages are called libhildon
- A user searching for libhildon in maemo-lesto repositories will not find correct package

I propose to rename the repository hildon -> libhildon.

**Comment by MerlijnWajer** [comment]
OK with me, just let us know so that we can update jenkins.

**Comment by spinal84** [comment]
Renamed.

**Comment by MerlijnWajer** [comment]
I removed 'hildon' and added 'libhildon' to Jenkins
