### ISSUE TITLE
--with-maemo-gtk=no is broken

### ISSUE THREAD

**Issue by marmistrz** [maemo-leste/libhildon#6]
Currently it's impossible to compile libhildon with upstream Gtk, because it uses types and functions from maemo-gtk. 

It appears that compatibility with upstream Gtk was neglected when the library was developed by Nokia. For example, the latest release from repository.maemo.org will use `hildon_gtk_entry_get_input_mode` without checking for the `MAEMO_GTK`.

#5 partially addresses this issue so that it's possible to build the library at the very least.

**Comment by spinal84** [comment]
Fixed by https://github.com/maemo-leste/libhildon/pull/5 and https://github.com/maemo-leste/libhildon/pull/8

**Comment by PureTryOut** [comment]
Well, #8 isn't merged yet, so I wouldn't close this issue til it is.

**Comment by spinal84** [comment]
@PureTryOut, thanks for suggestion.
The issue was closed by #5 
#8 is just a regression fix

**Comment by PureTryOut** [comment]
Ah, good, nvm me then!
